Repository TeamMody/mody-front, pull requests merged in 2025-02, with the labels that each got.

#97 ✨ Feat: 체형 분석 api 연결
  src/pages/home/components/BodyTypeContent.tsx
  src/pages/home/feature/hooks/mutate/usePostBodyAnalysis.ts
  src/pages/home/ui/BodySurveyPage.tsx
  src/pages/home/ui/BodyTypePage.tsx
  src/pages/home/ui/StyleSurveyPage.tsx
  src/shared/apis/body/body.ts
  src/shared/assets/icon/ic-body-type-natural.svg
  src/shared/assets/icon/ic-body-type-wave.svg
  src/shared/types/body/body.ts
  src/shared/types/index.ts
Labels: API 🧬, Feat 🔧, 홈 🏠

#100 ✨ Feat : 게시글 생성 API 연결
  src/app/routes/Router.tsx
  src/pages/my/components/BottomSheetItem.tsx
  src/pages/my/components/modal/EditUserInfoModal.tsx
  src/pages/post/apis/createPost.ts
  src/pages/post/apis/createPresignedUrl.ts
  src/pages/post/apis/createS3Url.ts
  src/pages/post/components/CreatePost.tsx
  src/pages/post/components/modal/CreateNewPostModal.tsx
  src/pages/post/components/toggleButton.tsx
  src/pages/post/hooks/useCreatePost.ts
  src/shared/store/token.ts
Labels: API 🧬, Feat 🔧, 게시글 📝

#101 🎨 Feat: #16 전역변수로 설정된 내 정보 profileHeader 와 연결
  src/pages/my/components/MyBodyTypeCard.tsx
  src/pages/my/components/ProfileHeader.tsx
  src/pages/my/components/modal/SettingModal.tsx
  src/pages/my/ui/MyPage.tsx
  src/pages/post/apis/createPresignedUrl.ts
  src/pages/post/apis/createS3Url.ts
  src/shared/store/token.ts
  src/shared/ui/BottomNavigation.tsx
Labels: Style 🎨, 마이페이지 👤

#107 ✨ Feat: #99 마이페이지 부가 기능
  src/pages/my/components/MyAndLikePosts.tsx
  src/pages/my/components/NoPosts.tsx
  src/pages/my/hooks/useGetInfinitePosts.ts
  src/shared/apis/my.ts
  src/shared/types/my/my.ts
  src/shared/types/props.ts
Labels: Feat 🔧

#108 ✨ Feat: 나의 체형 정보 조회 API 연결 작업
  src/pages/home/ui/BodyTypePage.tsx
  src/pages/my/components/MyAndLikePosts.tsx
  src/pages/my/components/MyBodyTypeCard.tsx
  src/pages/my/components/ProfileHeader.tsx
  src/pages/my/hooks/mutate/useGetBodyTypeResult.ts
  src/pages/my/hooks/query/useGetInfinitePosts.ts
  src/pages/my/ui/MyPage.tsx
  src/shared/apis/body/body.ts
  src/shared/store/token.ts
Labels: API 🧬, Feat 🔧, 마이페이지 👤

#115 🐛 Fix: modal close 이슈 수정
  src/pages/my/components/BottomSheetItem.tsx
  src/pages/my/features/store/useModalState.ts
Labels: Feat 🔧, Bug 🐛

#124 ✨ : Feat/#120 로그아웃 api 연결 완료
  src/pages/my/components/modal/ConfirmationModal.tsx
  src/pages/my/hooks/query/useLogOut.ts
Labels: API 🧬, 마이페이지 👤

#126 ✨ Feat: 게시글 수정 UI 및 API 연결
  src/app/routes/Router.tsx
  src/pages/my/components/BottomSheetItem.tsx
  src/pages/post/components/PostBottom.tsx
  src/pages/post/components/modal/CreateNewPostModal.tsx
  src/pages/post/hooks/usePatchPost.tsx
  src/pages/post/ui/EditPostPage.tsx
  src/shared/apis/post/post.ts
  src/shared/types/props.ts
  src/shared/ui/EditBottomSheetModal.tsx
  src/shared/ui/Post.tsx
Labels: API 🧬, Style 🎨, 게시글 📝

#131 ♻️ Refactor: 좋아요 낙관적 업데이트 및 MyPage 개선
  src/main.tsx
  src/pages/home/feature/hooks/mutate/usePostLikeEvent.ts
  src/pages/home/feature/hooks/mutate/usePostRecommendations.ts
  src/pages/home/feature/store/useRecommendationResultStore.ts
  src/pages/home/ui/HomePage.tsx
  src/pages/my/components/Profile.tsx
  src/pages/my/components/ProfileHeader.tsx
  src/pages/my/hooks/mutate/useGetBodyTypeResult.ts
  src/pages/my/hooks/query/useGetInfiniteRecommendations.ts
  src/pages/my/hooks/useControlModal.ts
  src/pages/my/ui/MyPage.tsx
Labels: Refactor ♻️, 마이페이지 👤

#134 :sparkles: Feat: 마이페이지 탭바 상태관리
  src/pages/my/components/MiddleTabBar.tsx
  src/pages/my/components/MyAndLikePosts.tsx
  src/pages/my/components/MyPageContentLayout.tsx
  src/pages/my/components/NoPosts.tsx
  src/pages/my/components/Post.tsx
  src/pages/my/components/RecommendResults.tsx
  src/pages/my/components/SlideIndicator.tsx
  src/pages/my/components/modal/ConfirmationModal.tsx
  src/pages/my/features/store/usePostIdStore.ts
  src/pages/my/features/store/useTabBarStore.ts
  src/pages/my/hooks/query/useGetInfinitePosts.ts
  src/pages/my/hooks/query/useGetInfiniteRecommendations.ts
  src/pages/my/ui/PostDetailPage.tsx
  src/shared/types/props.ts
Labels: Feat 🔧, 마이페이지 👤

#142 ♻ Refactor: modal state hook 으로 변경
  .env
  src/pages/my/components/MyBodyTypeCard.tsx
  src/pages/my/hooks/useControlModal.ts
  src/pages/post/apis/createS3Url.ts
  src/pages/post/components/CreatePost.tsx
  src/pages/post/components/modal/CreateNewPostModal.tsx
  src/pages/post/components/modal/SelectPhotoBottomSheetModal.tsx
  src/shared/ui/ImageCarousel2.tsx
Labels: Refactor ♻️

#145 ✨ Feature: #139 게시글 수정 API 추가 및 수정
  src/pages/my/components/BottomSheetItem.tsx
  src/pages/my/components/MyAndLikePosts.tsx
  src/pages/my/components/modal/EditBottomSheetModal.tsx
  src/pages/my/hooks/mutate/useDeletePost.ts
  src/pages/my/hooks/query/useGetInfinitePosts.ts
  src/pages/post/components/PostBottom.tsx
  src/pages/post/components/modal/CreateNewPostModal.tsx
  src/pages/post/components/modal/EditBottomSheetModal.tsx
  src/pages/post/components/toggleButton.tsx
  src/pages/post/hooks/usePatchIsPublic.ts
  src/pages/post/hooks/usePatchPost.ts
  src/pages/post/ui/EditPostPage.tsx
  src/shared/apis/post/post.ts
  src/shared/ui/Post.tsx
Labels: API 🧬, Feat 🔧, 게시글 📝

#152 ♻️ Refactor: 홈 화면 일부 수정
  src/pages/home/components/Banner.tsx
  src/pages/home/ui/BodySurveyPage.tsx
  src/pages/home/ui/BodyTypePage.tsx
  src/pages/home/ui/StyleSurveyPage.tsx
  src/pages/onboarding/feature/hooks/useLoginMutation.ts
  src/shared/assets/icon/ic-body-type-natural.svg
  src/shared/assets/icon/ic-body-type-wave.svg
  src/shared/types/body/body.ts
  src/shared/types/gloobal.d.ts
Labels: Refactor ♻️, 홈 🏠

#146 ♻️ Refactor/#143 bottomSheetModal 구조 변경 및 이미지 최적화
  package-lock.json
  package.json
  src/app/routes/Router.tsx
  src/pages/post/apis/createPost.ts
  src/pages/post/apis/createPresignedUrl.ts
  src/pages/post/apis/createS3Url.ts
  src/pages/post/components/ConvertToWebP.tsx
  src/pages/post/components/CreatePost.tsx
  src/pages/post/components/HeicToJpeg.tsx
  src/pages/post/components/ImgLayout.tsx
  src/pages/post/components/PostBottom.tsx
  src/pages/post/components/modal/CreateNewPostModal.tsx
  src/pages/post/components/modal/SelectPhotoBottomSheetModal.tsx
  src/pages/post/index.ts
  src/pages/post/ui/CameraPage.tsx
  src/pages/post/ui/CapturedImgPage.tsx
  src/shared/ui/CreatePostImageCarousel.tsx
Labels: Refactor ♻️, 게시글 📝

#157 ♻️ Refactor: Home 화면 개선
  src/pages/home/components/Banner.tsx
  src/pages/home/components/BodyTypeContent.tsx
  src/pages/home/components/MainRecommendation.tsx
  src/pages/home/components/SubBanner.tsx
  src/pages/home/components/SubRecommendation.tsx
  src/pages/home/ui/BodyTypePage.tsx
  src/pages/home/ui/RecommendationResultPage.tsx
  src/pages/my/ui/PostDetailPage.tsx
  src/pages/onboarding/feature/hooks/useLoginMutation.ts
Labels: Refactor ♻️, 홈 🏠

#160 ♻️ Refactor: 마이페이지 및 게시글 페이지 리팩토링
  src/pages/my/components/BottomSheetItem.tsx
  src/pages/my/components/MiddleTabBar.tsx
  src/pages/my/components/MyAndLikePosts.tsx
  src/pages/my/components/MyPageContentLayout.tsx
  src/pages/my/components/NoPosts.tsx
  src/pages/my/components/Post.tsx
  src/pages/my/components/RecommendResults.tsx
  src/pages/my/components/SlideIndicator.tsx
  src/pages/my/ui/PostDetailPage.tsx
  src/pages/post/components/PostBottom.tsx
  src/pages/post/components/modal/EditBottomSheetModal.tsx
  src/pages/post/hooks/usePatchPost.ts
  src/pages/post/hooks/usePostLike.ts
  src/pages/post/ui/EditPostPage.tsx
  src/pages/post/ui/PostPage.tsx
  src/shared/apis/my.ts
  src/shared/apis/post/post.ts
  src/shared/types/post/post.ts
  src/shared/ui/Post.tsx
Labels: Refactor ♻️, 게시글 📝, 마이페이지 👤

#162 ♻️ Refactor : 게시글 생성 페이지 불필요한 리랜더링 해결
  src/pages/post/components/CreatePost.tsx
  src/pages/post/components/PostBottom.tsx
  src/pages/post/components/modal/CreateNewPostModal.tsx
  src/pages/post/feature/apis/createPost.ts
  src/pages/post/feature/apis/createPresignedUrl.ts
  src/pages/post/feature/utils/convertToWebP.ts
  src/pages/post/feature/utils/createS3Url.ts
  src/pages/post/hooks/useCreatePost.ts
  src/pages/post/ui/EditPostPage.tsx
  src/shared/ui/CreatePostImageCarousel.tsx
Labels: Refactor ♻️, 게시글 📝

#166 ♻️ Refactor: 내 정보 추출 로지 변경
  src/pages/home/components/RecommendationLoading.tsx
  src/shared/store/useMyInfoStore.ts
Labels: Refactor ♻️, 홈 🏠

#173 ✨ Feat: #164 스타일 추천 모달 버튼 navigate 추가
  src/pages/my/components/modal/RecommendationModal.tsx
  src/shared/ui/CreatePostImageCarousel.tsx
Labels: Feat 🔧, 마이페이지 👤

#174 ♻️ Refactor: 자잘한 개선 작업
  src/pages/home/ui/StyleSurveyPage.tsx
  src/pages/my/ui/MyPage.tsx
  src/pages/onboarding/pages/OnboardingPage.tsx
  src/pages/post/ui/PostPage.tsx
Labels: Refactor ♻️, 홈 🏠

#179 🎨 Style: 체형 설문 페이지 Animation 효과 적용
  src/pages/home/components/Question.tsx
Labels: Style 🎨, 홈 🏠

#178 🐛 Fix/#172 게시글 수정 줌 버튼 활성화
  src/pages/post/components/PostBottom.tsx
  src/pages/post/ui/EditPostPage.tsx
  src/shared/ui/ImageCarousel.tsx
  src/shared/ui/ProgressBar.tsx
Labels: Bug 🐛, 게시글 📝
