Repository TeamMody/mody-front, pull requests merged in 2025-01, with the labels that each got.

#21 Init/#19 init setting
  index.html
  package-lock.json
  package.json
  src/app/App.tsx
  src/app/layout/RootLayout.tsx
  src/app/layout/index.ts
  src/app/providers/AppRouterProvider.tsx
  src/app/providers/AppThemeProvider.tsx
  src/app/providers/QueryProvider.tsx
  src/app/providers/index.ts
  src/app/routes/Router.tsx
  src/app/routes/index.ts
  src/app/styles/colors.ts
  src/app/styles/fonts.ts
  src/app/styles/global-style.ts
  src/app/styles/index.ts
  src/app/styles/theme.ts
  src/pages/home/index.ts
  src/pages/home/ui/HomePage.tsx
  src/pages/my/index.ts
  src/pages/my/ui/MyPage.tsx
  src/pages/onboarding/index.ts
  src/pages/onboarding/ui/OnboardingPage.tsx
  src/pages/post/index.ts
  src/pages/post/ui/PostPage.tsx
  src/shared/assets/icon/ic-home.tsx
  src/shared/assets/icon/ic-inbox.tsx
  src/shared/assets/icon/ic-user.tsx
  src/shared/config/index.ts
  src/shared/config/query-client.ts
  tsconfig.app.json
  vite.config.ts
Labels: Init 🎉

#24 :art: style/#23 : MyBodyTypeCard 컴포넌트 구현
  src/app/layout/RootLayout.tsx
  src/app/providers/AppRouterProvider.tsx
  src/app/routes/Router.tsx
  src/main.tsx
  src/pages/home/ui/HomePage.tsx
  src/pages/my/components/MyBodyTypeCard.tsx
  src/pages/my/ui/MyPage.tsx
  src/pages/post/ui/PostPage.tsx
  src/shared/assets/icon/ic-home.tsx
  src/shared/assets/icon/ic-inbox.tsx
  src/shared/assets/icon/ic-left-arrow.svg
  src/shared/assets/icon/ic-right-arrow.svg
  src/shared/assets/icon/ic-right-arrow.tsx
  src/shared/assets/icon/ic-user.tsx
  src/shared/ui/AppBar.tsx
  src/shared/ui/BottomNavigation.tsx
Labels: Style 🎨, 마이페이지 👤

#29 :art: Style: #17 홈 화면 UI
  src/app/routes/Router.tsx
  src/pages/home/components/Banner.tsx
  src/pages/home/components/SubBanner.tsx
  src/pages/home/ui/HomePage.tsx
  src/shared/assets/img/img-banner-body-type.png
  src/shared/assets/img/img-banner-item.png
  src/shared/assets/img/img-banner-style.png
  src/shared/assets/img/img-sub-banner-situation.png
  src/shared/assets/img/img-sub-banner-weather.png
  src/shared/ui/BottomNavigation.tsx
Labels: Style 🎨, 홈 🏠

#27 :art: style: #15 중앙 tabbar 구현
  package-lock.json
  package.json
  src/pages/my/components/LikedPosts.tsx
  src/pages/my/components/MiddleTabBar.tsx
  src/pages/my/components/MyPosts.tsx
  src/pages/my/components/RecommendResults.tsx
  src/pages/my/components/RenderTabContent.tsx
  src/pages/my/components/SlideIndicator.tsx
  src/pages/my/ui/MyPage.tsx
  src/shared/assets/icon/ic-grid.tsx
  src/shared/assets/icon/ic-heart.tsx
  src/shared/assets/icon/ic-hexagon.tsx
Labels: Style 🎨, 마이페이지 👤

#32 🎨 : style/#25 Modal 컴포넌트 구현
  src/app/styles/fonts.ts
  src/pages/my/components/MyBodyTypeCard.tsx
  src/pages/my/components/modal/ConfirmationModal.tsx
  src/pages/my/components/modal/RecommendationModal.tsx
  src/pages/my/ui/MyPage.tsx
  src/shared/assets/icon/ic-cancel.svg
  src/shared/assets/icon/ic-cancel.tsx
  src/shared/assets/icon/ic-right-arrow.tsx
Labels: Style 🎨, 마이페이지 👤

#33 🎨 style: #31 탭별 컴포넌트 구현
  src/pages/my/components/LikedPosts.tsx
  src/pages/my/components/MyPosts.tsx
  src/pages/my/components/NoPosts.tsx
  src/pages/my/components/Post.tsx
  src/pages/my/components/RecommendResults.tsx
  src/pages/my/components/RenderTabContent.tsx
  src/pages/my/components/TabContents.tsx
  src/pages/my/ui/MyPage.tsx
Labels: Style 🎨, 마이페이지 👤

#22 :art: style/#16 Profile Header 컴포넌트 구현 및 User Image 컴포넌트 구현
  src/pages/my/components/ProfileHeader.tsx
  src/pages/my/components/UserImg.tsx
  src/pages/my/features/mocks/JungHwiJune.png
  src/pages/my/features/mocks/userInfo.ts
  src/pages/my/ui/MyPage.tsx
  src/shared/assets/icon/ic-emptyProfileIcon.svg
  src/shared/assets/icon/ic-emptyProfileIcon.tsx
  src/shared/types/my/profileHeaderTypes.ts
Labels: Style 🎨, 마이페이지 👤

#35 :art: Style: #30 체형 타입 설문 화면 구현
  package-lock.json
  package.json
  src/app/routes/Router.tsx
  src/pages/home/components/Answer.tsx
  src/pages/home/components/Banner.tsx
  src/pages/home/components/Question.tsx
  src/pages/home/feature/store/useAnswersStore.ts
  src/pages/home/index.ts
  src/pages/home/ui/BodySurveyPage.tsx
  src/pages/home/ui/HomePage.tsx
  src/shared/apis/home/mocks.ts
  src/shared/types/home.ts
  src/shared/types/index.ts
  src/shared/ui/AppBar.tsx
  src/shared/ui/BottomNavigation.tsx
  src/shared/ui/CustomButton.tsx
Labels: Style 🎨, 홈 🏠

#40 :art: Style: 로딩 화면 & 체형 분석 결과 화면 구현
  src/app/routes/Router.tsx
  src/pages/home/index.ts
  src/pages/home/ui/BodySurveyPage.tsx
  src/pages/home/ui/BodyTypePage.tsx
  src/pages/home/ui/LoadingPage.tsx
  src/shared/assets/icon/ic-bg-loading.svg
  src/shared/assets/icon/ic-body-type-st.svg
  src/shared/assets/icon/ic-loading.svg
Labels: Style 🎨, 홈 🏠

#43 :art: Style: 스타일 추천 설문 및 결과 페이지 구현
  src/app/routes/Router.tsx
  src/pages/home/components/Banner.tsx
  src/pages/home/components/Keyword.tsx
  src/pages/home/components/StyleSurvey.tsx
  src/pages/home/index.ts
  src/pages/home/ui/LoadingPage.tsx
  src/pages/home/ui/RecommendationResultPage.tsx
  src/pages/home/ui/StyleSurveyPage.tsx
  src/shared/apis/home/mocks.ts
  src/shared/assets/icon/ic-loading-style.svg
  src/shared/types/home.ts
Labels: Style 🎨, 홈 🏠

#46 :art: Style/#16 좋아요 수 부분 수정
  src/pages/my/components/ProfileHeader.tsx
  src/pages/my/features/mocks/userInfo.ts
Labels: Style 🎨, 마이페이지 👤

#47 :art: style/#23 MyBodyTypeCard 수정
  src/pages/my/components/MyBodyTypeCard.tsx
Labels: Style 🎨, 마이페이지 👤

#49 🎨 Style: #39 내 게시글 편집 Bottom Sheet 구현
  package-lock.json
  package.json
  src/pages/my/components/BottomSheetItem.tsx
  src/pages/my/components/SlideIndicator.tsx
  src/pages/my/components/modal/EditBottomSheetModal.tsx
  src/pages/my/ui/MyPage.tsx
  src/shared/assets/icon/ic-grid.tsx
  src/shared/assets/icon/ic-heart.tsx
  src/shared/assets/icon/ic-hexagon.tsx
  src/shared/assets/icon/ic-pen.svg
  src/shared/assets/icon/ic-trash-can.svg
  src/shared/ui/ToggleButton.tsx
Labels: Style 🎨, 마이페이지 👤

#51 ♻️ : Refactor /#48 my page refactoring
  src/pages/my/components/MyPageContentLayout.tsx
  src/pages/my/ui/MyPage.tsx
Labels: Refactor ♻️, 마이페이지 👤

#53 🎨 : Style/#25 유저정보 수정 Modal 구현 완료
  package-lock.json
  package.json
  src/pages/my/components/MyBodyTypeCard.tsx
  src/pages/my/components/UserDataInput.tsx
  src/pages/my/components/modal/ConfirmationModal.tsx
  src/pages/my/components/modal/EditUserInfoModal.tsx
  src/pages/my/components/modal/RecommendationModal.tsx
  src/pages/my/components/modal/SettingModal.tsx
  src/pages/my/features/schema/MyUserInfoSchema.ts
  src/pages/my/ui/MyPage.tsx
  src/shared/types/my/modalProps.ts
  src/shared/types/my/profileHeaderTypes.ts
Labels: Style 🎨, 마이페이지 👤

#57 ♻️ Refactor: 로딩 및 홈 페이지 개선 작업
  package-lock.json
  src/app/routes/Router.tsx
  src/pages/home/components/Answer.tsx
  src/pages/home/components/BodyTypeContent.tsx
  src/pages/home/components/Loading.tsx
  src/pages/home/components/Question.tsx
  src/pages/home/components/SubBanner.tsx
  src/pages/home/index.ts
  src/pages/home/ui/BodySurveyPage.tsx
  src/pages/home/ui/BodyTypePage.tsx
  src/pages/home/ui/RecommendationResultPage.tsx
  src/pages/home/ui/StyleSurveyPage.tsx
  src/pages/my/ui/MyPage.tsx
  src/shared/apis/home/mocks.ts
Labels: Refactor ♻️, 홈 🏠

#61 :art: Style: #60 유저 정보 입력 UI 구현
  package-lock.json
  src/pages/home/components/Banner.tsx
  src/pages/home/components/MainRecommendation.tsx
  src/pages/onboarding/components/BirthdaySelector.tsx
  src/pages/onboarding/components/HeightSelector.tsx
  src/pages/onboarding/ui/InputUser.tsx
  src/pages/onboarding/ui/SecondPage.tsx
  src/pages/onboarding/utils/date.ts
  src/pages/onboarding/utils/scroll.ts
Labels: Style 🎨, 온보딩 🌐

#66 🎨 :Style/#23 padding 단위 변경
  src/pages/my/components/MyBodyTypeCard.tsx
Labels: Style 🎨, 마이페이지 👤

#65 🎨 : Style/#16 my profile header gap 수정 완료
  package-lock.json
  package.json
  src/pages/my/components/ProfileHeader.tsx
  src/pages/my/components/UserImg.tsx
Labels: Style 🎨, 마이페이지 👤

#69 :recycle: Refactor: 바텀네비게이션 새로고침 이슈 수정
  package-lock.json
  package.json
  src/shared/store/useBottomNavigationStore.ts
  src/shared/ui/BottomNavigation.tsx
Labels: Refactor ♻️

#73 🎨 :Style/#25 설정 Modal 크기 수정
  src/pages/my/components/modal/SettingModal.tsx
Labels: Style 🎨, 마이페이지 👤

#77 🎨 :Style/#25 Modal 컴포넌트 랜더링 문제 해결 시도
  src/pages/my/components/UserDataInput.tsx
  src/pages/my/components/modal/ConfirmationModal.tsx
  src/pages/my/components/modal/EditUserInfoModal.tsx
  src/pages/my/components/modal/RecommendationModal.tsx
  src/pages/my/components/modal/SettingModal.tsx
Labels: Style 🎨, 마이페이지 👤

#79 🎨 :Style/#25 SelectPhotoBottomSheetModal 컴포넌트 안에 있는 카메라 실행 구현
  package-lock.json
  package.json
  src/app/routes/Router.tsx
  src/pages/my/components/MyBodyTypeCard.tsx
  src/pages/my/components/modal/ConfirmationModal.tsx
  src/pages/my/components/modal/EditUserInfoModal.tsx
  src/pages/my/components/modal/RecommendationModal.tsx
  src/pages/post/components/CreatePost.tsx
  src/pages/post/components/modal/CreateNewPostModal.tsx
  src/pages/post/components/modal/SelectPhotoBottomSheetModal.tsx
  src/pages/post/index.ts
  src/pages/post/ui/CameraPage.tsx
  src/pages/post/ui/CapturedImgPage.tsx
  src/shared/ui/ImageCarousel.tsx
  src/shared/ui/ProgressBar.tsx
Labels: Style 🎨, 마이페이지 👤

#81 :art: Style:#75 체형 분석 일러스트 추가 작업
  src/pages/home/components/Answer.tsx
  src/pages/home/components/Question.tsx
  src/pages/home/ui/BodySurveyPage.tsx
  src/pages/home/ui/BodyTypePage.tsx
  src/pages/home/ui/RecommendationResultPage.tsx
  src/pages/home/ui/StyleSurveyPage.tsx
  src/shared/apis/home/mocks.ts
  src/shared/assets/icon/body/ic-body-characteristics-one.svg
  src/shared/assets/icon/body/ic-body-characteristics-two.svg
  src/shared/assets/icon/body/ic-body-chest-one.svg
  src/shared/assets/icon/body/ic-body-chest-three.svg
  src/shared/assets/icon/body/ic-body-chest-two.svg
  src/shared/assets/icon/body/ic-body-collarbone-one.svg
  src/shared/assets/icon/body/ic-body-collarbone-three.svg
  src/shared/assets/icon/body/ic-body-collarbone-two.svg
  src/shared/assets/icon/body/ic-body-flesh-one.svg
  src/shared/assets/icon/body/ic-body-flesh-three.svg
  src/shared/assets/icon/body/ic-body-flesh-two.svg
  src/shared/assets/icon/body/ic-body-girl-shoulder-four.svg
  src/shared/assets/icon/body/ic-body-girl-shoulder-one.svg
  src/shared/assets/icon/body/ic-body-girl-shoulder-three.svg
  src/shared/assets/icon/body/ic-body-girl-shoulder-two.svg
  src/shared/assets/icon/body/ic-body-hip-one.svg
  src/shared/assets/icon/body/ic-body-hip-three.svg
  src/shared/assets/icon/body/ic-body-hip-two.svg
  src/shared/assets/icon/body/ic-body-leg-girl-one.svg
  src/shared/assets/icon/body/ic-body-leg-girl-two.svg
  src/shared/assets/icon/body/ic-body-leg-man-one.svg
  src/shared/assets/icon/body/ic-body-leg-man-two.svg
  src/shared/assets/icon/body/ic-body-man-shoulder-four.svg
  src/shared/assets/icon/body/ic-body-man-shoulder-one.svg
  src/shared/assets/icon/body/ic-body-man-shoulder-three.svg
  src/shared/assets/icon/body/ic-body-man-shoulder-two.svg
  src/shared/assets/icon/body/ic-body-neck-four.svg
  src/shared/assets/icon/body/ic-body-neck-one.svg
  src/shared/assets/icon/body/ic-body-neck-three.svg
  src/shared/assets/icon/body/ic-body-neck-two.svg
  src/shared/assets/icon/body/ic-body-skin-one.svg
  src/shared/assets/icon/body/ic-body-skin-three.svg
  src/shared/assets/icon/body/ic-body-skin-two.svg
  src/shared/assets/icon/body/ic-body-thigh-girl-one.svg
  src/shared/assets/icon/body/ic-body-thigh-girl-three.svg
  src/shared/assets/icon/body/ic-body-thigh-girl-two.svg
  src/shared/assets/icon/body/ic-body-thigh-man-one.svg
  src/shared/assets/icon/body/ic-body-thigh-man-three.svg
  src/shared/assets/icon/body/ic-body-thigh-man-two.svg
  src/shared/assets/icon/body/ic-body-waist-one.svg
  src/shared/assets/icon/body/ic-body-waist-two.svg
  src/shared/types/home.ts
Labels: Style 🎨, 홈 🏠

#84 :bug: Fix: 빌드 에러 해결
  package-lock.json
  package.json
  src/app/routes/Router.tsx
Labels: Bug 🐛

#93 ✨ Feat: 스타일 분석 API 연결
  src/pages/home/feature/hooks/mutate/usePostStyleAnalysis.ts
  src/pages/home/feature/hooks/query/useGetStyleCategories.ts
  src/pages/home/ui/RecommendationResultPage.tsx
  src/pages/home/ui/StyleSurveyPage.tsx
  src/shared/apis/member/member.ts
  src/shared/apis/style.ts
  src/shared/apis/style/style.ts
  src/shared/types/index.ts
  src/shared/types/style/style.ts
Labels: API 🧬, 홈 🏠

#94 🎨 Style:#92 게시물 로딩 UI 변경
  package-lock.json
  package.json
  src/pages/my/components/MyAndLikePosts.tsx
  src/shared/ui/SmallLoading.tsx
Labels: Style 🎨, 마이페이지 👤
